service: 
    name: iot-trigger-test
custom:
    tableName: 'iot-trigger-table-${self:provider.stage}'    
provider:
 name: aws
 runtime: nodejs8.10
 memorySize: 128
 timeout: 10
 stage: production
 region: us-east-1
 iamRoleStatements:
    - Effect: Allow
      Action:
       - dynamodb:PutItem
      Resource:
       - { "Fn::GetAtt": ["PostFetchDynamoDBTable", "Arn" ] }

functions:
    iotTrigger: 
        handler: index.handler

resources:
  Resources:
    PostFetchDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: transactionId
            AttributeType: S
        KeySchema:
          - AttributeName: transactionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}        